package com.gamegards.gaming27;

public enum GAMES {
 /*   JACKPOT_3PATTI,
    COLOUR_PREDICTION1,
    COLOUR_PREDICTION_VERTICAL,
    DRAGON_TIGER,
    ROULETTE,
    SEVEN_UP_DOWN,
    AVIATOR_VERTICAL;*/

    TEENPATTI,
    DRAGON_TIGER,
    ANDHAR_BAHAR,
    POINT_RUMMY,
    PRIVATE_RUMMY,
    POOL_RUMMY,
    DEAL_RUMMY,
    PRIVATE_TABLE,
    CUSTOM_TABLE,
    SEVEN_UP_DOWN,
    CAR_ROULETTE,
    JACKPOT_3PATTI,
    ANIMAL_ROULETTE,
    COLOUR_PREDICTION,
    POKER_GAME,
    HEAD_TAIL,
    RED_BLACK,
    LUDO_GAME_PLAY_LOCAL,
    LUDO_GAME_ONLINE,
    LUDO_GAME_COMPUTER,
    BACCARAT,
    JHANDHI_MUNDA,
    ROULETTE,
    ROULETTE_DOUBLE,

    TOURNAMENT,
    COLOUR_PREDICTION1,
    COLOUR_PREDICTION3,
    AVIATOR,
    COLOUR_PREDICTION30,
    AVIATOR_VERTICAL;
}
